### ISSUE TITLE
Non-specific digestion

### ISSUE THREAD

**Issue by lonelu** [pFindStudio/pGlyco3#1]
1. When the file path contains space, such as 'my folder', the program could not work. When the path is changed to 'my_folder', it works. 
2. Not a bug, but the change of enzyme is a pain now (pGlyco2 is nice). For example, I want nonspecfic sesarch and put 
![image](https://user-images.githubusercontent.com/10702896/110199040-3f7f9d00-7e0b-11eb-91a1-474516d80dae.png)
Not sure if it is right...

**Comment by jalew188** [comment]
Thank you @lonelu .

Some users had reported bug 1 to me, I will fix it in the next version.

For 2, I have not yet added a non-specific digestion module in pGlyco3. You may do this:
```
Name: whatever
Digest N-Term:
Digest C-Term: ABCDEFGHIJKLMNOPQRSTUVWXYZ
Max Miss: 25
```

**Comment by adribick** [comment]
@lonelu Did this work for you? I am also interested in non-specific digestion and the solution above gave me; [pGlyco Error] bad allocation

**Comment by jalew188** [comment]
@adribick I believe it only works for small fasta files, not proteome-wide fasta

**Comment by adribick** [comment]
@jalew188 This works. Thank you.
