### ISSUE TITLE
关于PlausibleStruct的问题

### ISSUE THREAD

**Issue by 1931046** [pFindStudio/pGlyco3#10]
您好：
请问pGlyco结果中的PlausibleStruct是从其他糖数据库中导入的还是根据糖合成规则自己推算的?因为结果中有一些PlausibleStruct在GlyTouCan糖库中找不到

**Comment by jalew188** [comment]
有些是来自最复杂的Complex糖结构的子结构，有可能不在GlyTouCan中。
