### ISSUE TITLE
关于Multi-site-O-glycan糖型的问题

### ISSUE THREAD

**Issue by 1931046** [pFindStudio/pGlyco3#11]
您好：
         我的搜索结果中有一些糖型是 (N(H(F)(N(H))))(N(H)(N(H(H(F)))))，根据这个结果我画出来的糖型是这个样子，请问是有这样的O-糖基化存在吗？还是我理解错误了？
H             H-F
 |               |
N             H
 |               |
H-F    H   N
 |          \ / 
N          N
 \          /
   \      /
     \  /
 PEPTIDE

**Comment by jalew188** [comment]
这是个多糖链，需要进一步确定位点才能真正确定有几个结构。

**Comment by jalew188** [comment]
不排除N糖和O糖同时存在的可能性
