### ISSUE TITLE
搜索出问题

### ISSUE THREAD

**Issue by baixue123456** [pFindStudio/pGlyco3#12]
![image](https://user-images.githubusercontent.com/95457097/144536981-6f5ec680-5765-455b-97d5-0d64bb2ae864.png)

**Comment by jalew188** [comment]
Please check pGlyco3.log or pGlyco.log for details. @baixue123456

**Comment by baixue123456** [comment]
[](url
[pGlyco3.log](https://github.com/pFindStudio/pGlyco3/files/7658891/pGlyco3.log)
)

**Comment by jalew188** [comment]
No such a director: "E:\pGlyco\Yu" . Maybe you can remove the space in the path, and then try again.
