### ISSUE TITLE
关于pGlyco结果筛选的问题

### ISSUE THREAD

**Issue by xiashj3027** [pFindStudio/pGlyco3#18]
您好！请问pGlyco输出的结果中，如何根据三个分值（total score，peptide score和glycan score）初步筛选所要保留的结果呢？是否有推荐的cut off值？此外，如果total score很高，但对应的pepscore和glyscore其中一个很低，通常这种结果怎么处理呢？是否需要逐张检查PSM图？谢谢！

**Comment by jalew188** [comment]
目前的报表都是已经经过FDR筛选过的，匹配质量都是比较高的。不建议单独筛选，除非要看某一条特定的糖肽。

如果真要单独筛选，最好还是用pepscore和glyscore，这样能够保证肽和糖的匹配质量都较高。

**Comment by xiashj3027** [comment]
了解了，感谢！
&nbsp;
&nbsp;
------------------&nbsp;Original&nbsp;------------------
From: ***@***.***&gt;;
Date: &nbsp;Sun, Oct 9, 2022 03:24 PM
To: ***@***.***&gt;; 
Cc: ***@***.***&gt;; ***@***.***&gt;; 
Subject: &nbsp;Re: [pFindStudio/pGlyco3] 关于pGlyco结果筛选的问题 (Issue #18)

&nbsp;



 
目前的报表都是已经经过FDR筛选过的，匹配质量都是比较高的。不建议单独筛选，除非要看某一条特定的糖肽。
 
如果真要单独筛选，最好还是用pepscore和glyscore，这样能够保证肽和糖的匹配质量都较高。
