### ISSUE TITLE
Totally unrelated support request

### ISSUE THREAD

**Issue by zrolfs** [pFindStudio/pGlyco3#2]
Hello,
I'm having issues using pTop and I was unable to send an e-mail to ptop@ict.ac.cn. pGlyco3 is the most recently updated pFindStudio repository, so I'm taking a shot in the dark that somebody might see this.

I just downloaded pTop v2.0 and installed it. However, when I open the application, I get a notification that says “Software has expired, please download and install it again”.
Any help is appreciated.

Best,
Zach Rolfs
Post-Doc
Lloyd Smith Lab
Department of Chemistry
University of Wisconsin-Madison

**Comment by jalew188** [comment]
@zrolfs Sorry for the late reply. pTop may be no longer under maintainance any more due to the lack of man power. I am not 100% sure as I left pFind Lab since last year

**Comment by zrolfs** [comment]
Thank you for the reply! Bummer to hear that pTop might be dead. I haven't received a response to any of the e-mails I sent to the group, so I appreciated hearing from you. Hope all is well.
