### ISSUE TITLE
Incorrect amino acid in result

### ISSUE THREAD

**Issue by elcientifico** [pFindStudio/pGlyco3#20]
I've been using pGlyco3 for some searches and I've noticed that it will substitute J for N .  For example, I will run a search with only one protein that has a sequence 'MNDT' and the result will say that the peptide sequence for this protein is 'MJDT'.  In the PeptideMH column with will report the mass for 'MNDT' + 1: 480.158 

Perhaps this has something to do with the mass of Isoleucine and Leucine being 1 less than for N.

**Comment by jalew188** [comment]
Peptide MH refers to the mass of peptide plus a proton

**Comment by elcientifico** [comment]
Thanks.  That's what I noted in the original comment.  The issue is that in the results pGlyco3 changes the **N** to a **J** even though the PeptideMH will match the expected value for M**N**DT.

If the PeptideMH value is the mass of 'MNDT' + 1 (proton mass), why does pGlyco3 say that the sequence is M**J**DT ? the  M**J**DT  PeptideMH is smaller than  M**N**DT PeptideMH

**Comment by jalew188** [comment]
Ahh, we replaced all N by J with motif N-X-S/T/C.
