### ISSUE TITLE
Files missing from download

### ISSUE THREAD

**Issue by maddie1893** [pFindStudio/pGlyco3#22]
I have downloaded pGlyco3.0_build20210615. When looking at the user manual for gLabel you need a few files. The ones I can not fine in anything I downloaded or other files on here are for the MGF section and the pGlycoRes section. I have searched my computer and all the files that can with the zip file and they are not there. Where can I find these files

**Comment by jalew188** [comment]
Please check user guide (https://github.com/pFindStudio/pGlyco3/blob/main/pGlyco3-User-Guide.pdf)
MGF is the MS file you searched
pGlycoRes is the result file you got after pGlyco3 search

**Comment by maddie1893** [comment]
I realize now the MGF file. I was confused on that because I used a mzML file in the first part. When I run the first part of the program I get a .cfg file, but the pGlycoRes wants a .txt file. Do I just need to convert the file?
