### ISSUE TITLE
Converting Glycoworkbench file to gdb file

### ISSUE THREAD

**Issue by lindaz711** [pFindStudio/pGlyco3#3]
I'm having problems with converting a gwp file to gdb file using pGlyco3. The issue seems to be that the program does not recognize the phosphates ("p", "1P" in gwp) that were used in the gwp file. The phosphate was not defined in the configuration file "glycoworkbench_to_gdb.ini" since it was not a glycan, so I modified the "glyco.ini" to make do. But is there a way to have the program convert gwp files that contain glycan structures with modifications such as phsophorylation, sulfation, nitrosylation, and acetylation?

**Comment by jalew188** [comment]
We do not support phosphates for glycoworkbench in current version of pGlyco3. But we can create a GDB based on something like this:
![image](https://user-images.githubusercontent.com/4646029/122604581-77d38000-d076-11eb-9692-9a598102af96.png)
And then replacing X (Xyl) with pH.
