### ISSUE TITLE
Processing Error

### ISSUE THREAD

**Issue by Yungstedt** [pFindStudio/pGlyco3#30]
I'm running the latest release, but the program stopped at this error:
Process ID=03148: Unhandled Exception: System.IO.FileNotFoundException: Could not load file or assembly 'Base, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null' or one of its dependencies. The system cannot find the file specified.
Process ID=03148:    at CombineMS2.Program.Main(String[] args)

**Comment by Yungstedt** [comment]
Another error happend when converting O-glycan gdb from gwp
Traceback (most recent call last):
  File "glycoworkbench_to_gdb.py", line 211, in <module>
  File "glycoworkbench_to_gdb.py", line 196, in ReadOneGWP
  File "glycoworkbench_to_gdb.py", line 116, in generate_subtree_by_gwb
  File "glycoworkbench_to_gdb.py", line 93, in generate_subtree_by_gwb
UnboundLocalError: local variable 'i' referenced before assignment
[15384] Failed to execute script 'glycoworkbench_to_gdb' due to unhandled exception!

**Comment by jalew188** [comment]
> I'm running the latest release, but the program stopped at this error: Process ID=03148: Unhandled Exception: System.IO.FileNotFoundException: Could not load file or assembly 'Base, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null' or one of its dependencies. The system cannot find the file specified. Process ID=03148: at CombineMS2.Program.Main(String[] args)

This seems like .NET version's problem, check `dotnet --version`

**Comment by jalew188** [comment]
> Another error happend when converting O-glycan gdb from gwp Traceback (most recent call last): File "glycoworkbench_to_gdb.py", line 211, in File "glycoworkbench_to_gdb.py", line 196, in ReadOneGWP File "glycoworkbench_to_gdb.py", line 116, in generate_subtree_by_gwb File "glycoworkbench_to_gdb.py", line 93, in generate_subtree_by_gwb UnboundLocalError: local variable 'i' referenced before assignment [15384] Failed to execute script 'glycoworkbench_to_gdb' due to unhandled exception!

This is indeed a but due to I changed the python version from 2.7 to 3.9. You can download it from the release page now: https://github.com/pFindStudio/pGlyco3/releases

**Comment by Yungstedt** [comment]
> > I'm running the latest release, but the program stopped at this error: Process ID=03148: Unhandled Exception: System.IO.FileNotFoundException: Could not load file or assembly 'Base, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null' or one of its dependencies. The system cannot find the file specified. Process ID=03148: at CombineMS2.Program.Main(String[] args)
> 
> This seems like .NET version's problem, check `dotnet --version`

I checked I installed .NET 6.0 and 8.0, with 3.5 feature enabled in Windows 10. Could you please tell me what is the targeting version of pGlyco3?

**Comment by Yungstedt** [comment]
> > Another error happend when converting O-glycan gdb from gwp Traceback (most recent call last): File "glycoworkbench_to_gdb.py", line 211, in File "glycoworkbench_to_gdb.py", line 196, in ReadOneGWP File "glycoworkbench_to_gdb.py", line 116, in generate_subtree_by_gwb File "glycoworkbench_to_gdb.py", line 93, in generate_subtree_by_gwb UnboundLocalError: local variable 'i' referenced before assignment [15384] Failed to execute script 'glycoworkbench_to_gdb' due to unhandled exception!
> 
> This is indeed a bug due to I changed the python version from 2.7 to 3.9. I have fixed it int he new version. You can download it from the release page now with _pyinstaller-6.0.0_ from https://github.com/pFindStudio/pGlyco3/releases

I started by testing conversion of N-glycan database this time, but it encountered a new error below.

Already registered!
N
Traceback (most recent call last):
  File "glycoworkbench_to_gdb.py", line 211, in <module>
  File "glycoworkbench_to_gdb.py", line 196, in ReadOneGWP
  File "glycoworkbench_to_gdb.py", line 93, in generate_subtree_by_gwb
UnboundLocalError: local variable 'j' referenced before assignment
[2916] Failed to execute script 'glycoworkbench_to_gdb' due to unhandled exception!

**Comment by jalew188** [comment]
> > > I'm running the latest release, but the program stopped at this error: Process ID=03148: Unhandled Exception: System.IO.FileNotFoundException: Could not load file or assembly 'Base, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null' or one of its dependencies. The system cannot find the file specified. Process ID=03148: at CombineMS2.Program.Main(String[] args)
> > 
> > 
> > This seems like .NET version's problem, check `dotnet --version`
> 
> I checked I installed .NET 6.0 and 8.0, with 3.5 feature enabled in Windows 10. Could you please tell me what is the targeting version of pGlyco3?

I think all .NET framework versions fine, there may be some issues on diff version of .NET core
