### ISSUE TITLE
Issue importing GlycoWorkbench file (gwp)

### ISSUE THREAD

**Issue by trvadams** [pFindStudio/pGlyco3#33]
Hello, have run into a problem while using pGlyco3.1_build20231220 on Windows 11.
When trying to import a GlycoWorkbench file to make a custom N-glycan database, I get the following error:
```
N(NH(HNH)HNH)F
Traceback (most recent call last):
  File "glycoworkbench_to_gdb.py", line 211, in <module>
  File "glycoworkbench_to_gdb.py", line 196, in ReadOneGWP
  File "glycoworkbench_to_gdb.py", line 93, in generate_subtree_by_gwb
UnboundLocalError: local variable 'j' referenced before assignment
[31656] Failed to execute script 'glycoworkbench_to_gdb' due to unhandled exception!
```
I am attempting this with a .gwp file containing single structure as seen below. If I try multiple structures, it gives the same error.
![image](https://github.com/pFindStudio/pGlyco3/assets/51549805/76cb0147-2ba2-44db-8655-bd2e2c4c7c31)

Are there any workarounds to this problem, or alternatives for converting gws formatted sequences to gdb?

**Comment by jalew188** [comment]
Hi @trvadams , yes, this is a bug when I change python version from 2.7 to 3.x. We are working on this

**Comment by jalew188** [comment]
Please check https://github.com/pFindStudio/pGlyco3/issues/34 for the solution

**Comment by trvadams** [comment]
> Please check #34 for the solution

This works, thanks so much.
