### ISSUE TITLE
Peptide decoy 

### ISSUE THREAD

**Issue by Xindong-Sun** [pFindStudio/pGlyco3#39]
Hi Wenfeng, 

May I kindly ask if pGlyco3 could generate a peptide decoy itself, or a fasta file with decoy is required. 

Thanks a lot.

Cheers,
Xindong

**Comment by jalew188** [comment]
Decoy is automatically generated in pGlyco3

**Comment by Xindong-Sun** [comment]
Cool. Thanks a lot. Also huge congrats on your new jouney at Westlake! 

Cheers,
Xindong
