### ISSUE TITLE
申请pGlyco3-用户指南

### ISSUE THREAD

**Issue by kuibayishi** [pFindStudio/pGlyco3#9]
你好，pGlyco3-用户指南无法下载了，请问可以重新上传一下吗？

**Comment by yangjq28773** [comment]
你好，pGlyco3-用户指南无法下载,网页打不开，请问可以重新上传一下吗？

**Comment by yangjq28773** [comment]
你好，pGlyco3-用户指南无法下载,网页打不开，请问可以重新上传一下吗？

**Comment by jalew188** [comment]
可能是因为某些因素不能访问github，候选地址为https://figshare.com/articles/online_resource/pGlyco3_User_Guide/21096799
